### ISSUE TITLE
Ignore type properties in AddTable() method

### ISSUE THREAD

**Issue by tstanitz** [RasicN/Dapper-Parameters#5]
Hello,

What do you think about the option to be able to ignore properties in the AddTable() method to not transform to DynamicParameter.  It would be useful when the collection has more properties than the SP expected. 

Or is it possible somehow other? Or is it mandatory for the collection to have a same properties as the SP expects?

Thanks,
Tamas

**Comment by tstanitz** [comment]
I have created a pull request #6 if you fine with it

**Comment by tstanitz** [comment]
Hello,

@RasicN when do you plan to release a new nuget version?

Thanks,
Tamas

**Comment by RasicN** [comment]
I have pushed a new version just now https://www.nuget.org/packages/Dapper.ParameterExtensions/2018.8.1.1
Let me know if you have any issues and sorry for the long delay on this!

**Comment by tstanitz** [comment]
Thanks a lot, I'll update in our solution

Br,
Tamas
